### ISSUE TITLE
Python does not recognize random.choices()

### ISSUE THREAD

**Issue by utk-dev** [utk-dev/URL-Processor#1]
`import random`
`import string`
`def urlmaker():`
`    while(True):`
`        a = ''.join(i for i in random.choices(string.ascii_letters,k=6))`
`        return a`

the code given above does not work specifically in [utils.py](https://github.com/utk-dev/URL-Processor/blob/master/short/utils.py).

And I don't see any other `random` named entity (module, method etc.) masking/hiding the random module provided by Python.  
@libhide @deadbeatfour your thoughts (I know the code is in a really bad shape.)

**Comment by libhide** [comment]
The issue is with your call to `join`. `join` takes a sequence as far as I know and you're giving it elements. 

![screen shot 2017-12-24 at 4 47 16 pm](https://user-images.githubusercontent.com/1370559/34326060-66d35a10-e8ca-11e7-9d90-c0c4e684e495.png)

**Comment by deadbeatfour** [comment]
Yeah, @libhide is right. If, however, your error message is the issue title, I'd suggest checking your python version. I think `random.choices()` was added in python 3.6 and your code runs on my system running 3.6.3. 
![screenshot 2017-12-24 18 56 17](https://user-images.githubusercontent.com/12121913/34326836-44822704-e8dc-11e7-86a0-96c155c1e6a3.png)

**Comment by utk-dev** [comment]
@libhide I wanted to make a string of six characters. Your code appends all the brackets and commas of the list as well. @deadbeatfour is right; my virtual environment had installed Python 3.5.2
![Old version](https://user-images.githubusercontent.com/25015384/34327420-37a1f1fa-e8ea-11e7-80c0-885792b209de.PNG)

@libhide and @deadbeatfour thanks for the help.
![New version](https://user-images.githubusercontent.com/25015384/34327421-3ce112ea-e8ea-11e7-9a16-669918a3cb3b.PNG)
